<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Catalog\Catalog.csproj" />
    <ProjectReference Include="..\..\Modules\Ordering\Ordering.csproj" />
    <ProjectReference Include="..\..\Modules\Basket\Basket.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>